### ISSUE TITLE
Hotkey to open Squad Manager window directly

### ISSUE THREAD

**Issue by Almdoodler** [xvwyh/SquadRoles#2]
Currently there is no way to set a hotkey to open the Squad Manager window. Using the window in the current state feels kinda cumbersome since I have to navigate through the ArcDPS settings, at least the first time after each game start, to reach it.

I do know there is the ability to minimize the window into just the titlebar, but even with it minimized it does take up quite some screenspace, therefore I propose adding

- a hotkey/key combination that opens the window directly
- and (optionally) the ability to customize said hotkey to personal preferences, similar to how the killproof.me addon allows this

I know there will probably be more pressing issues but I'd love to see this implemented in the future

**Comment by xvwyh** [comment]
I will add customizable keybinds in the next update.

**Comment by xvwyh** [comment]
Implemented in version [2024-09-18](https://github.com/xvwyh/SquadRoles/releases/tag/2024-09-18).
